# Default values for gitops setup

global:
  render: true
  argocd:
    enabled: true
    controller: openshift-operators
  operators: 
    enabled: true
  rbac: 
    enabled: true 
  namespace: openshift-operators
  domain: sandbox2414.opentlc.com
  # sharding: <amount_of_sno>  
  sno:
  #   1: 
  #     token: <token>
  #     username: <username>
  #     password: <password>
